#------------------------------------------------------------------------------
# NOTE: This code was generated by a build tool using repo
# (the-container-store/Java-Docker-Project-Template#master).
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated. Please use the documentation provided
# in http://the-container-store.github.io/Gradle-Releaser/ to see
# how to regenerate this file based on your project settings.
#------------------------------------------------------------------------------
FROM containerstore/java-17-jdk AS builder
LABEL image="preston-integrations-proposal-services-build"

# The default timezone is UTC.  In cases where the timezone needs to be overridden, uncomment the following line.
# ENV TZ=America/Chicago
ARG VERSION=0.0.0-0-0000000
ARG VAULT_TOKEN=provide-build-arg-to-override

WORKDIR /home/builder

# Download gradle and all of our dependencies
COPY gradle/ /home/builder/gradle
COPY gradlew build.gradle settings.gradle gradle.properties /home/builder/
RUN ./gradlew --no-daemon downloadDependencies

COPY . /home/builder/
RUN VAULT_TOKEN=$VAULT_TOKEN \
    ./gradlew --no-daemon \
    buildReleaseCandidate \
    stageDockerArtifacts \
    -PexternallySuppliedVersion=$VERSION

# copy artifacts and package image
FROM containerstore/java-17-jre:17.0
ARG APP_BUILDTIME=UNSET
ARG APP_NAME=preston-integrations-proposal-services
ARG APP_VERSION=0.0.0-0-0000000
ENV APP_BUILDTIME=$APP_BUILDTIME \
    APP_NAME=$APP_NAME \
    APP_VERSION=$APP_VERSION
LABEL image=$APP_NAME
LABEL image.created=$APP_BUILDTIME
LABEL image.version=$APP_VERSION

# The default timezone is UTC.  In cases where the timezone needs to be overridden, uncomment the following line.
# ENV TZ=America/Chicago

WORKDIR /home/app
COPY --from=builder --chown=app:applications /home/builder/build/docker/* ./

#
# Install prerequisites
#
RUN chmod +x *.sh \
	&& /home/app/yum-install-prerequisites.sh

USER app
EXPOSE 8080

CMD consul-template \
        --once \
        -template "/home/app/shim.sh:/home/app/shim.sh" \
        -log-level=info \
        -exec "/home/app/shim.sh"

HEALTHCHECK --retries=8 CMD curl --silent --fail http://localhost:8080/about?dockerfile || exit 1
