package com.containerstore.prestonintegrations.proposal.shared.proposalconstants.enums;

public enum ProposalConstantKeys {
	MINIMUM_INSTALLATION_FEE, INSTALLATION_RATE, MAX_RETAIL_VALUE_PER_CRATE, THRESHOLD_AMOUNT_TO_CALCULATE_INSTALL_DAYS,
	AVERAGE_HOTEL_FEE, AVERAGE_PER_DIEM_FEE, NO_OF_INSTALLERS, MINIMUM_DRIVE_TIME, MINIMUM_MILEAGE, COST_PER_MILE
}
