#!/usr/bin/env bash
#------------------------------------------------------------------------------
# NOTE: This code was generated by a build tool using repo
# (the-container-store/Java-Docker-Project-Template#master).
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated. Please use the documentation provided
# in http://the-container-store.github.io/Gradle-Releaser/ to see
# how to regenerate this file based on your project settings.
#------------------------------------------------------------------------------
set -e
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

IMAGE_TAG=$1
APP_BUILDTIME=$(date +%F_%T)
APP_NAME="preston-integrations-proposal-services"
SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIRECTORY="$( dirname ${SCRIPT_DIRECTORY} )"

if [ -z "${IMAGE_TAG}" ]; then
  IMAGE=containerstore/$APP_NAME:latest
  echo "No image specified... building ${IMAGE}"
  docker build --force-rm --pull --build-arg APP_BUILDTIME=$APP_BUILDTIME -t $IMAGE "${PROJECT_DIRECTORY}"
else
  IMAGE=containerstore/$APP_NAME:$IMAGE_TAG
fi

# Default to dev if deployment environment is not
if [ -z ${DEPLOYMENT_ENVIRONMENT} ]; then
  DEPLOYMENT_ENVIRONMENT=dev
fi

command -v vault >/dev/null 2>&1 || { printf >&2 "${YELLOW}vault${NC} (https://www.vaultproject.io) is ${YELLOW}required${NC}. Ensure it is installed\n"; exit 1; }

if [ ! -f ~/.vault-token ]; then
  echo "Please login to vault using ${YELLOW}vault login${NC}"
fi

docker run \
  --rm \
  -p 8080:8080 \
  --hostname $APP_NAME-localdev \
  --name $APP_NAME-localdev \
  -e APP_NAME=$APP_NAME \
  -e DEPLOYMENT_ENVIRONMENT=$DEPLOYMENT_ENVIRONMENT \
  -e DEPLOYMENT_STACK=preview \
  -e CONSUL_HTTP_ADDR=http://consul.containerstore.com:8500 \
  -e VAULT_ADDR=https://vault.containerstore.com \
  -e VAULT_TOKEN=$(cat ~/.vault-token) \
  $IMAGE
